#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  deploy_shared_verifier.sh --verifier-sol <path> --contract-name <name> --rpc-url <url> --private-key <key>

Options:
  --verifier-sol   Solidity verifier file generated by bb
  --contract-name  Contract name to deploy as (default: ZusVerifier)
  --rpc-url        RPC URL for deployment
  --private-key    Deployer private key
  -h, --help       Show this help
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERIFIER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

VERIFIER_SOL=""
GENERATED_CONTRACT_NAME="UltraVerifier"
CONTRACT_NAME="ZusVerifier"
RPC_URL=""
PRIVATE_KEY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verifier-sol)
      VERIFIER_SOL="${2:-}"
      shift 2
      ;;
    --contract-name)
      CONTRACT_NAME="${2:-}"
      shift 2
      ;;
    --rpc-url)
      RPC_URL="${2:-}"
      shift 2
      ;;
    --private-key)
      PRIVATE_KEY="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${VERIFIER_SOL}" || -z "${RPC_URL}" || -z "${PRIVATE_KEY}" ]]; then
  echo "--verifier-sol, --rpc-url, and --private-key are required" >&2
  usage >&2
  exit 1
fi

VERIFIER_SOL="$(cd "$(dirname "${VERIFIER_SOL}")" && pwd)/$(basename "${VERIFIER_SOL}")"
if [[ ! -f "${VERIFIER_SOL}" ]]; then
  echo "Could not find verifier Solidity file at ${VERIFIER_SOL}" >&2
  exit 1
fi

if [[ ! "${CONTRACT_NAME}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
  echo "Invalid Solidity contract name: ${CONTRACT_NAME}" >&2
  exit 1
fi

TARGET_SOL="${VERIFIER_DIR}/src/${CONTRACT_NAME}.sol"
cp "${VERIFIER_SOL}" "${TARGET_SOL}"

if [[ "${CONTRACT_NAME}" != "${GENERATED_CONTRACT_NAME}" ]]; then
  perl -0pi -e "s/contract[[:space:]]+${GENERATED_CONTRACT_NAME}\\b/contract ${CONTRACT_NAME}/g" "${TARGET_SOL}"
fi

echo "==> Deploying ${CONTRACT_NAME} from ${TARGET_SOL}"
forge create \
  --root "${VERIFIER_DIR}" \
  --rpc-url "${RPC_URL}" \
  --private-key "${PRIVATE_KEY}" \
  "src/${CONTRACT_NAME}.sol:${CONTRACT_NAME}"
